-- MySQL Script generated by MySQL Workbench
-- Mon Jun  6 12:11:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Restaurapp
-- -----------------------------------------------------
 DROP SCHEMA IF EXISTS `Restaurapp` ;

-- -----------------------------------------------------
-- Schema Restaurapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restaurapp` DEFAULT CHARACTER SET utf8 ;
USE `Restaurapp` ;

-- -----------------------------------------------------
-- Table `Restaurapp`.`Adiciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurapp`.`Adiciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Value` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Restaurapp`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurapp`.`Categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Image` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Restaurapp`.`Categoria_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurapp`.`Categoria_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_categoria` INT NOT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Restaurapp`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurapp`.`Producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(150) NOT NULL,
  `Description` VARCHAR(300) NOT NULL,
  `Short_Description` VARCHAR(100) NOT NULL,
  `Value` INT NOT NULL,
  `Image` TEXT NOT NULL,
  `Image_Galery` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


